### ISSUE TITLE
Factom-walletd not syncing

### ISSUE THREAD

**Issue by khelle** [FactomProject/factom-walletd#51]
Hello, everyone!
I have installed latest Factom distribution on Ubuntu v16.04 system, using following lines:

```
wget https://github.com/FactomProject/distribution/releases/download/v0.4.2.21/factom-amd64.deb
dpkg -i factom-amd64.deb
mkdir /home/fct/.factom
mdkir /home/fct/.factom/m2
mkdir /home/fct/.factom/wallet
```

Then I copied exemplary configuration file (https://raw.githubusercontent.com/FactomProject/factomd/master/factomd.conf) into /home/fct/.factom/m2/factomd.conf

I started both services via:

```
/usr/bin/factomd -ControlPanelPort 15225 -port 15226
/usr/bin/factom-walletd -p 15227 -s localhost:15226
```

Then I opened ports 15225, 15226, 15227 and 8110 (p2p) ports in my firewall. Services seem to run properly, they do not throw any errors and both of their APIs is responsive and working. However, for some reason my wallet service is not syncing from factomd.

factomd API `heights` returns me `{"jsonrpc":"2.0","id":1,"result":{"directoryblockheight":134439,"leaderheight":134440,"entryblockheight":134439,"entryheight":132015}}`

whil factom-walletd API `get-height` returns `{"jsonrpc":"2.0","id":1,"result":{"height":0}}`.

Did I miss something to make it work properly? This might be connected to issue #50 .

**Comment by i3bitcoin** [comment]
Yes, #50 is the same issue. Walletd returns "height":0.

**Comment by khelle** [comment]
@i3bitcoin did you find a way to solve this issue perhaps?

**Comment by carryforward** [comment]
Yes, this is the main API wallet still.  We know it could use some optimization and some better feedback, though.  


Mainnet p2p is on port 8108, not 8110, which is for the testnet for example.  It looks like you are at block 134000, so that implies the mainnet. That isn't the problem here though.

The first time the wallet runs, it will populate a local cache of the factoid blocks in `~/.factom/wallet/factom_wallet.cache`  This happens in the background, and starts the first time transactions are asked for when starting up.  Even with low latency between factomd and factom-walletd, the syncing between the two programs can take an hour.  After it syncs once, factom-walletd will only need to get the latest blocks since it last synced.

My suggestion is to get factomd synced locally, then run factom-walletd.  Run `factom-cli listtxs` which will kick off the transaction syncing between the two programs.  you can ctrl+c factom-cli, as it will take a while.  you can watch the modified file time of the `factom_wallet.cache` file to see when it is done syncing the first time.  (I haven't tested the wallet height API call when it is initially syncing.)

See if this fixes your issue.
